name: alfresco-sync-service
version: 0.3.0
description: Alfresco Syncservice
keywords:
- syncservice
- alfresco
- application
# home:
# sources:
#   -
maintainers:
- name: Alfresco Apps Repo Team
engine: gotpl
