# Defines the properties required by the sync-service app
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "syncservice.fullname" . }}-configmap
  labels:
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    component: syncservice
data:
  JAVA_OPTS: >-
      {{- if eq .Values.database.external false }}
      -Dsql.db.driver="org.postgresql.Driver"
      -Dsql.db.url=jdbc:postgresql://{{ printf "%s-%s" .Release.Name .Values.postgresql.nameOverride }}:{{ .Values.postgresql.service.port }}/{{ .Values.postgresql.postgresDatabase }}
      {{- else }}
      -Dsql.db.driver={{ .Values.database.driver}}
      -Dsql.db.url={{ .Values.database.url}}
      {{- end }}
      -Ddb.username=$DATABASE_USERNAME
      -Ddb.password=$DATABASE_PASSWORD
      -Drepo.hostname={{ .Values.repository.host }}
      -Drepo.port={{ .Values.repository.port }}
      -Dmessaging.broker.host={{ .Values.activemq.broker.host }}
      -Dmessaging.username={{ .Values.activemq.broker.username }}
      -Dmessaging.password={{ .Values.activemq.broker.password }}
      -Ddw.server.applicationConnectors[0].type=http
      {{ .Values.syncservice.environment.JAVA_OPTS }}
