apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "syncservice.fullname" . }}
  labels:
    app: {{ template "syncservice.fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "syncservice.fullname" . }}
        release: {{ .Release.Name }}
    spec:
      imagePullSecrets:
        - name: {{ .Values.registryPullSecrets }}
      initContainers:
      - name: init-activemq
        image: busybox
        env:
        - name: ACTIVEMQ_HOST
          value: {{ .Values.activemq.broker.host | quote }}
        - name: ACTIVEMQ_PORT
          value: {{ .Values.activemq.broker.ports.openwire | default 61616 | quote }}
        command: ['sh', '-c', 'until nc -w1 $ACTIVEMQ_HOST $ACTIVEMQ_PORT; do echo "waiting for activemq"; sleep 5; done;']      
      - name: init-postgres
        image: busybox
        command: ['sh', '-c', 'until nc -w1 {{ .Release.Name }}-postgresql-syncservice 5432; do echo "waiting for postgresql"; sleep 2; done;']
      containers:
      - name: syncservice
        image: "{{ .Values.syncservice.image.repository }}:{{ .Values.syncservice.image.tag }}"
        imagePullPolicy: {{ .Values.syncservice.image.pullPolicy }}
        env:
        - name: JAVA_TOOL_OPTIONS
          value: |- 
                {{- if eq .Values.database.external false }}
                -Dsql.db.driver="org.postgresql.Driver"
                -Dsql.db.url=jdbc:postgresql://{{ printf "%s-%s" .Release.Name .Values.postgresql.nameOverride }}:{{ .Values.postgresql.service.port }}/{{ .Values.postgresql.postgresDatabase }}
                -Ddb.username={{ .Values.postgresql.postgresUser | b64enc }}
                -Ddb.password={{ .Values.postgresql.postgresPassword | b64enc }}
                {{- else }}
                -Dsql.db.driver={{ .Values.database.driver}}
                -Dsql.db.url={{ .Values.database.url}}
                -Ddb.username={{ .Values.database.user  }}
                -Ddb.password={{ .Values.database.password }}
                {{- end }}
                -Drepo.hostname={{ .Values.repository.host }}
                -Drepo.port={{ .Values.repository.port }}
                -Dmessaging.broker.host={{ .Values.activemq.broker.host }}
                -Ddw.server.applicationConnectors[0].type=http


        ports:
        - name: serviceport
          containerPort: 9090
        resources:
{{ toYaml .Values.syncservice.resources | indent 12 }}
        livenessProbe:
          httpGet:
            path: /alfresco/healthcheck
            port: serviceport
          initialDelaySeconds: 10
          periodSeconds: 10