{{- if .Values.networkpolicysetting.enabled }}
# Allow activemq to communicate with syncservice
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: syncservice-activemq
spec:
  podSelector:
    matchLabels:
      app: {{ printf "%s-%s" .Values.contentServices.installationName "activemq" }}
  policyTypes:
  - Ingress
  
  ingress:
    - from:
      # Allow syncservice to communicate with activemq
      - podSelector:
          matchLabels:
            app: {{ template "syncservice.fullname" . }}
{{- end }}
